Django/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbs/',include('bbs1.urls')),
]

bbs1/urls.py
from django.urls import path
from . import views

app_name ='bbs1'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('register/',views.RegisterView.as_view(),name='register'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('music/',views.MusicView.as_view(),name='music'),
    path('logout/',views.logout,name='logout'),
]

bbs1/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=10)
    password= models.CharField(max_length=10)

bbs1/views.py
from django.shortcuts import render,redirect,reverse
from django.contrib import messages
from django.views import View
from .form import UserForm
from .models import User
from .decorators import login_deco
from django.utils.decorators import method_decorator
# Create your views here.

@method_decorator(login_deco,name='dispatch')
class IndexView(View):
    def get(self,request):
        return render(request,'bbs1/index.html')



class RegisterView(View):
    def get(self,request):
        return render(request,'bbs1/register.html')

    def post(self,request):
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            err = form.errors.get_json_data()
            print(err)

            messages.info(request,err)
        return render(request,'bbs1/register.html')



class LoginView(View):
    def get(self,request):
        return render(request,'bbs1/login.html')

    def post(self,request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        usermx = User.objects.filter(username__exact=username,password__exact=password).first()
        if usermx:
            request.session['user_id'] = usermx.id
            request.session.set_expiry(0)
            return redirect(reverse('bbs1:index'))
        else:
            messages.info(request,'帐号密码错误')
            return render(request,'bbs1/login.html')



@method_decorator(login_deco,name='dispatch')
class MusicView(View):
    def get(self,request):
        return render(request, 'bbs1/music.html')




def logout(request):
    del request.session['user_id']
    return redirect(reverse('bbs1:login'))

templates/bbs1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">内容管理系统</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'bbs1:index' %}">index <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'bbs1:music' %}">music</a></li>
      </ul>
{#      <form class="navbar-form navbar-left">#}
{#        <div class="form-group">#}
{#          <input type="text" class="form-control" placeholder="Search">#}
{#        </div>#}
{#        <button type="submit" class="btn btn-default">Submit</button>#}
{#      </form>#}
        {% if user_info %}
                  <ul class="nav navbar-nav navbar-right">
        <li><a href="javascript:void(0)">欢迎您:{{ user_info.username }}</a></li>
        <li class="dropdown">
          <a href="{% url 'bbs1:logout' %}">退出 </a>
        {% else %}
            <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'bbs1:register' %}">注册</a></li>
            <li class="dropdown"><a href="{% url 'bbs1:login' %}">登录 </a>
        {% endif %}


        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    {% for message in messages %}
        <h2>{{ message }}</h2>
    {% endfor %}
{% block body %}


{% endblock %}
</body>
</html>

templates/bbs1/index.html
{% extends 'bbs1/base.html' %}

{% block body %}
    主页内容
{% endblock %}

templates/bbs1/login.html
{% extends 'bbs1/base.html' %}

{% block body %}
    <h2>登录</h2>
    <form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>用户名:</td>
            <td><input type="text" name="username" value="admin"></td>
        </tr>
        <tr>
            <td>密码：</td>
            <td><input type="password" name="password" value="admin"></td>
        </tr>
        <tr>
            <td><input type="submit" value="登录"></td>
        </tr>
    </table>
    </form>



{% endblock %}

templates/bbs1/music.html
{% extends 'bbs1/base.html' %}

{% block body %}
    我的音乐列表
{% endblock %}

templates/bbs1/register.html
{% extends 'bbs1/base.html' %}

{% block body %}
       <h2>注册</h2>
    <form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>用户名:</td>
            <td><input type="text" name="username"></td>
        </tr>
        <tr>
            <td>密码：</td>
            <td><input type="password" name="password"></td>
        </tr>
        <tr>
            <td>重复密码:</td>
            <td><input type="password" name="password1"></td>
        </tr>
        <tr>
            <td><input type="submit" value="登录"></td>
        </tr>
    </table>
    </form>

{% endblock %}